volkamerlab/opencadd

devtools/conda-envs/test_env.yaml
Pin biopython to 1.77 to workaround the `Bio.Alphabet` deprecation. The code in `opencadd.structure.superposition.sequences` will have to be updated at some point to remove this pin (it's not too complicated) but for now we'll just prevent 1.78 from being installed.
See https://github.com/volkamerlab/opencadd/pull/44#issuecomment-689367674 for more details.
=> Pin biopython to 1.77 for now

.github/workflows/ci.yaml
`add-path` and `set-env` commands are deprecated and will be disabled on November 16th. More information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
=> Update `setup-miniconda` to v2

opencadd/structure/pocket/core.py, opencadd/structure/pocket/klifs.py, opencadd/structure/pocket/subpocket.py
So far, in order to work with a structure in the `pocket` module, a local copy of its structure file was needed to satisfy the `Pocket` class method `visualize` (`nglview` visualization of structure/pocket). 
This was mainly the case because I could not make it work to show a structure from text in the mol2 format - but I figured it out now. Let's look at our options: 
```python
import nglview
view = nglview.show_file(filepath)
view = nglview.show_text(pdb_text)
structure = nglview.adaptor.TextStructure(text, ext="mol2")
view = nglview.widget.NGLWidget(structure)
```
In this PR, the `pocket` module is updated in a way that `Pocket` class can be initialized from a file but also from text. 
This is helpful for the `KlifsPocket` subclass, where we fetch data via KLIFS IDs. Before, the file …
=> Pocket visualization

docs/tutorials/databases_klifs.ipynb, opencadd/databases/klifs/core.py, opencadd/databases/klifs/remote.py, opencadd/tests/databases/test_klifs_local_remote.py
The KLIFS OpenAPI offers one more API: Get bioactivities by ligand Expo ID. 
Add this functionality to the `remote` module of `opencadd.databases.klifs`.
None.
=> Add Bioactivties.by_ligand_expo_id for remote module

devtools/conda-envs/test_env.yaml, docs/tutorials/databases_klifs.ipynb, opencadd/databases/klifs/local.py, opencadd/tests/databases/test_klifs_local_remote.py
`opencadd.databases.klifs` allows interaction with local KLIFS data. 
So far, it was only possible to get pocket information (i.e. residue PDB ID to KLIFS index mapping) based on mol2 files. 
In this PR, we add the same based on pdb files (KLIFS offers both mol2 and pdb files as download).
None
=> Enable pocket retrieval from local pdb files

opencadd/databases/klifs/local.py, opencadd/databases/klifs/remote.py, opencadd/databases/klifs/session.py, opencadd/databases/klifs/utils.py
Problem fixed by @jaimergp 
PR description by @dominiquesydow  
Using `bravado`'s `SwaggerClient` in a multiprocessing protocol causes a `RecursionError`.
```bash
from multiprocessing import Pool
from bravado.client import SwaggerClient
API_DEFINITIONS = "https://klifs.net/swagger/swagger.json"
CLIENT = SwaggerClient.from_url(API_DEFINITIONS, config={"validate_responses": False})
pool = Pool(processes=2)
type_list = pool.map(type, [CLIENT, CLIENT])
print(type_list)
pool.close()
pool.join()
```
```bash
Process ForkPoolWorker-2:
Traceback (most recent call last):
File "/home/dominique/.local/miniconda/envs/kissim/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
self.run()
File "/home/dominique/.local/miniconda/envs/kissim/lib/python3.8/multiprocessing/process.py", line …
```
=> fix serialization errors in bravado through subclassing

opencadd/databases/klifs/local.py
Handle unexpected KLIFS pockets. Detailed description: #86
=> Raise exceptions for unexpected KLIFS pockets

docs/installing.rst, opencadd/structure/superposition/cli.py, opencadd/structure/superposition/engines/mmligner.py
MMLigner does not find significant alignments, if the structures are too different.
This results in an UnboundLocalError.
In this case, the RMSD and coverage will be set to 0 and it is printed, that the method did not found an alignment.
Updated the documentation on installing for the workaround with updated MMLigner. This workaround is already used in the CI.
This should fix the issue #71.
=> MmLigner fix

opencadd/__init__.py
We'd like to submit `opencadd` to `conda-forge`. The package consists of quite different submodules, whose development status vary a lot; add a disclaimer!
Notable points that this PR has either accomplished or will accomplish.
None.
=> Add disclaimer about dev stages for different submodules

opencadd/__init__.py
Use logger instead of print, cleaning up https://github.com/volkamerlab/opencadd/pull/95.
That way other packages can specify if this message shall be shown or not.
None.
=> Module disclaimer: Use logger instead of print

opencadd/structure/pocket/viewer.py
In `opencadd.structure.pocket.viewer` module: `nglview` throws `TypeError` for `add_sphere` because sphere center given as `numpy.float` but must be now `float`.
None.
=> Pocket: Cast sphere center coordinates numpy.float > float

opencadd/databases/klifs/local.py, opencadd/databases/klifs/remote.py, opencadd/databases/klifs/session.py, opencadd/databases/klifs/utils.py, opencadd/tests/databases/test_klifs_remote_parallelization.py, opencadd/tests/databases/test_sync_klifs_and_opencadd.py
Trying to fix https://github.com/volkamerlab/opencadd/issues/102
None.
=> KLIFS module: RecursionError with parallelization... again!

opencadd/databases/klifs/local.py
When using the local module of `opencadd.databases.klifs`, we still query for KLIFS IDs (structure/ligand/kinase) remotely because those data points are not provided locally in the KLIFS download files.
If the local download contains structures that are not part of the database --- say you have downloaded data from https://klifs.net/ but our package calls https://dev.klifs.net/ --- you currently get a `SwaggerMappingError`. 
We will contact the KLIFS maintainers (https://github.com/volkamerlab/opencadd/issues/105) and add an try-except clause that will drop all local structures that are not available remotely
Notable points that this PR has either accomplished or will accomplish.
None
=> KLIFS: Drop remotely unavailable structures from local database

docs/tutorials/io.ipynb, opencadd/databases/klifs/local.py, opencadd/databases/klifs/remote.py, opencadd/io/__init__.py, opencadd/structure/pocket/core.py, opencadd/structure/pocket/viewer.py, opencadd/tests/io/test_biopython.py, opencadd/tests/io/test_dataframes.py, opencadd/tests/io/test_rdkit.py
We'd like to enable user installations containing only dependencies for OpenCADD-KLIFS.
Currently, `opencadd.io`'s `__init__` file imports packages that are needed in different `opencadd` modules. Let's remove the imports and update all affected paths in the package and the docs.
Notable points that this PR has either accomplished or will accomplish.
None
=> Remove io __init__ imports (to enable OpenCADD-KLIFS only deps)

paper/paper.md
Follow-up PR to https://github.com/volkamerlab/opencadd/pull/125 where we added the statement of need to the OpenCADD-KLIFS documentation.
In this PR, update the paper w.r.t. to what we agreed on in the documentation.
None.
=> OpenCADD-KLIFS: Sync stat. of need in paper with docs (issue #124)

docs/installing.rst, docs/installing_opencadd_klifs.rst
Apply @mcs07's suggestion in issue https://github.com/volkamerlab/opencadd/issues/126:
Add note to installation for users who install `mamba` into existing `conda` installation (manual adding of `conda-forge` channel needed).
None.
=> Docs: Extend installation instructions (add `conda-forge` channel note)

opencadd/databases/klifs/core.py
Correct docstring for `"structure.rmsd1"` and `"structure.rmsd2"` in `StructuresProvider` class.
- RMSD1: RMSD between the structure and the reference template for the conserved pocket residues
- RMSD2: RMSD between the structure and the reference template for the full pocket
None
=> Update docstring for KLIFS RMSD values

docs/conf.py
Docs have been failing for some time now:
https://github.com/volkamerlab/opencadd/runs/7493006534?check_suite_focus=true#step:5:269
I think this happens due to a warning - you now have to set a language in the sphinx config (instead of `None`):
https://github.com/volkamerlab/opencadd/runs/7493006534?check_suite_focus=true#step:5:13
=> Docs: Set sphinx language from None to en

opencadd/structure/superposition/api.py
Universes can come with or without models. Currently, we only consider universes with models in our `superposition` module: the first model is selected for the alignment. After this selection, the object type changes from an MDA `Universe` to `AtomGroup`.
Example:
```python
structures = [Structure.from_pdbid("4y72"), Structure.from_pdbid("1xqz"), Structure.from_pdbid("1m17")]
align(structures, user_select=False, method=METHODS["mda"]);
f1, f2, f3 = ...  # Path to PDB files*
structures = [Structure.from_string(f1), Structure.from_string(f2), Structure.from_string(f3)]
align(structures, user_select=False, method=METHODS["mda"]);
```
*Download PBD files (terminal):
```bash
for pdb in 4y72 1xqz 1m17; do wget https://www.rcsb.org/structure/$pdb -o $pdb.pdb; done
```
Cast all universes …
=> Superposition: Cast universes w and w/o models to atom groups

.github/workflows/ci.yaml, .github/workflows/docs.yaml
Update GHA CI configs (prompted by conda fails).
=> Update GHA CI configs

.github/workflows/ci.yaml, .gitignore
This is a minor update to the CI workflow to make it run again with the current configurations. Ready to merge into main.
=> Update GHA actions in CI pipeline
